server:
  listen: 8080

  workers: 4 # number of worker processes by default no. of cores

  upstreams:
    - id: jsonplaceholder
      url: jsonplaceholder.typicode.com

  headers: 
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: 'Bearer $token'

  rules:
  
    - path: /
      upstreams: 
        - jsonplaceholder
    